project:
  type: website
  output-dir: docs

website:
  title: "Sujan Kakumanu - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes
        menu:
          - href: weekly-notes/week-01-notes.html
            text: Week 1
          - href: weekly-notes/week-02-notes.html
            text: Week 2
          - href: weekly-notes/week-03-notes.html
            text: Week 3
          - href: weekly-notes/week-04-notes.html
            text: Week 4
          - href: weekly-notes/week-05-notes.html
            text: Week 5
          - href: weekly-notes/week-06-notes.html
            text: Week 6
          - href: weekly-notes/week-07-notes.html
            text: Week 7
          - href: weekly-notes/week-09-notes.html
            text: Week 9
          - href: weekly-notes/week-10-notes.html
            text: Week 10
      - text: Assignments
        menu:
          - href: assignments/assignment_1/assignment1.html
            text: Assignment 1 - Census Data Exploration
          - href: assignments/assignment_2/Kakumanu_Sujan_Assignment2.html
            text: Assignment 2
          - href: assignments/assignment_3/midterm_script.html
            text: Assignment 3 Technical Appendix (Group Project)
          - href: assignments/assignment_3/midterm_presentation.html
            text: Assignment 3 Presentation (Group Project)
          - href: assignments/assignment_4/Kakumanu_Sujan_Assignment_4.html
            text: Assignment 4
      - text: Labs
        menu:
          - href: labs/lab0/scripts/lab0_template.html
            text: Lab 0
          - href: labs/lab-05-model-competition/lab5.html
            text: Lab 5            
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
